apiVersion: apps/v1
kind: Deployment
metadata:
  name: lapulya-bot
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lapulya-bot
  template:
    metadata:
      labels:
        app: lapulya-bot
    spec:
      containers:
        - name: lapulya-bot
          image: ghcr.io/1t1scool/lapulya_bot:IMAGE_TAG
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: BOT_TOKEN
            - name: VK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: VK_TOKEN
            - name: HIBP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: HIBP_API_KEY
            - name: SHODAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: SHODAN_API_KEY
            - name: LEAKCHECK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: LEAKCHECK_API_KEY
            - name: INTELX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: INTELX_API_KEY
            - name: DEHASHED_EMAIL
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: DEHASHED_EMAIL
            - name: DEHASHED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: DEHASHED_API_KEY
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: RAPIDAPI_KEY
            - name: GETCONTACT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: GETCONTACT_TOKEN
            - name: FACEPP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: FACEPP_API_KEY
            - name: FACEPP_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: FACEPP_API_SECRET
            - name: ALLOWED_USERS
              valueFrom:
                secretKeyRef:
                  name: lapulya-bot-secret
                  key: ALLOWED_USERS
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-secret
